import React from "react";
import { StyleSheet } from "react-native";
import { color } from "./Colors";

export const styles = StyleSheet.create({
  layout: {
    padding: 10,
    flex: 1,
    alignItems: "center",
    backgroundColor: "black",
    //justifyContent: "flex-start",
  },
  containerItems: {
    flex: 1,
    padding: 10,
    alignItems: "center",
  },
  listContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
  },
  inputContainer: {
    flexDirection: "row",
    marginTop: 10,
    marginBottom: 10,
  },
  inputColors: { text: color.grey_200, placeholder: color.blue_grey_600 },
  textInput: {
    width: "80%",
    borderRadius: 10,
    backgroundColor: "black",
  },
  submitButton: {
    width: "100%",
    backgroundColor: color.dark_blue,
    alignItems: "center",
    padding: 10,
    marginTop: 50,
    borderRadius: 10,
  },
  row: {
    justifyContent: "space-around",
    flexDirection: "row",
  },
  simpleBG: {
    flex: 1,
    backgroundColor: "black",
  },
  text: {
    color: "white",
    padding: 5,
  },
  frameElement: {
    alignItems: "center",
    width: "48%",
    backgroundColor: color.dark_blue,
    padding: 8,
    margin: 5,
    borderRadius: 10,
  },
  frameItem: {
    alignItems: "center",
    backgroundColor: color.blue_700,
    width: "75%",
    paddingVertical: 10,
    paddingHorizontal: 3,
    marginVertical: 10,
    marginHorizontal: 5,
    borderRadius: 10,
  },
  frameAddData: {
    alignItems: "center",
    backgroundColor: color.blue_600,
    width: "20%",
    padding: 8,
    margin: 5,
    borderRadius: 10,
  },
  frameIcon: {
    justifyContent: "center",
    alignItems: "center",
    width: "20%",
    borderRadius: 8,
    padding: 9,
  },
  button: {
    alignItems: "center",
    width: "48%",
    backgroundColor: color.blue_500,
    padding: 5,
    margin: 5,
    marginBottom: 12,
    borderRadius: 10,
  },
  button1: {
    alignItems: "center",
    width: "45%",
    backgroundColor: color.dark_blue,
    padding: 5,
    margin: 5,
    marginBottom: 10,
    borderRadius: 10,
  },
  modalAlert: {
    marginTop: 300,
    marginHorizontal: 20,
    backgroundColor: "rgba(38, 38, 38, 0.9)",
    flexDirection: "row",
    borderWidth: 1,
    borderColor: color.dark_blue,
    borderRadius: 10,
    padding: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  modalData: {
    marginTop: 270,
    marginBottom: 50,
    marginHorizontal: 26,
    backgroundColor: "rgba(10, 10, 15, 0.85)",
    borderWidth: 2,
    borderColor: color.dark_blue,
    borderRadius: 10,
    paddingBottom: 50,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  modalBG: { flex: 1, backgroundColor: "rgba(15, 15, 15, 0.8)" },
});
