version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      #      - ./scripts/db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql:/var/lib/mysql
